"""grade_class

Revision ID: 81e0b22de956
Revises: dbb91f38825f
Create Date: 2023-06-11 07:18:57.485029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e0b22de956'
down_revision = 'dbb91f38825f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
