"""init student

Revision ID: dbb91f38825f
Revises: 
Create Date: 2023-06-11 07:18:44.738614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb91f38825f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('class_name', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('class_name')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=True),
    sa.Column('surname', sa.String(length=127), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('grade',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'grade')
    )
    op.create_table('student_class_link',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=31), nullable=False),
    sa.ForeignKeyConstraint(['class_name'], ['class.class_name'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'class_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_class_link')
    op.drop_table('grade')
    op.drop_table('student')
    op.drop_table('class')
    # ### end Alembic commands ###
