"""grade_class

Revision ID: fc571d4782b5
Revises: 5049d029f002
Create Date: 2023-06-11 12:16:16.572459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc571d4782b5'
down_revision = '5049d029f002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('class_name', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('class_name')
    )
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_class_link',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=31), nullable=False),
    sa.ForeignKeyConstraint(['class_name'], ['class.class_name'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'class_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_class_link')
    op.drop_table('grade')
    op.drop_table('class')
    # ### end Alembic commands ###
